### ISSUE TITLE
"Reduce" the importance of the videos in the book

### ISSUE THREAD

**Issue by mauricioaniche** [sttp-book/sttp-book.github.io#12]
The videos are nice, but they really harm us when it comes to evolve the book... We should find a way to reduce its importance.

Maybe move them to the end of their respective chapters? And we make it clear that they are complementary, and that students should not expect one video per topic.

**Comment by sf105** [comment]
Perhaps it's more about using them as additional "interludes" in the material? Add short videos when you think it helps to get a point across.

**Comment by mauricioaniche** [comment]
I agree. After a skimming the book a bit, I feel that most videos will still be relevant. So, let's decide on a per-case basis, after we improve the text.
