### ISSUE TITLE
Order of chapter 6 and 7 seems to be switched

### ISSUE THREAD

**Issue by sback** [sttp-book/sttp-book.github.io#6]
Chapter 6 (Model-Based testing) talks about MC/DC and explains:
> We have already discussed MC/DC in the Structural-Based Testing chapter.

However, Structural-Based Testing will come as the 7th chapter. Maybe this is an indication that the order of the chapters is switched.

**Comment by mauricioaniche** [comment]
Done! Thanks for the suggestion!
